management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - threaddump
          - prometheus
    endpoint:
      shutdown:
        access: none
app:
  cache:
    ttl-minute: 30