spring:
  liquibase:
    change-log: classpath:db/changelog/master.yaml
  application:
    name: ms-account-reservation
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
#    по умолчанию для продюссера включил at most once
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 0
#    по умолчанию для консьюмера включил at most once
    consumer:
      group-id: ms-account-reservation-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: true
#            value:
#              default:
#                type: org.example.msaccountreservation.events.ClientChangedEvent
    listener:
      ack-mode: manual_immediate
management:
  server:
    port: ${MANAGEMENT_PORT:8081}
  endpoints:
    web:
      exposure:
        include: "health, threaddump"
  endpoint:
    shutdown:
      access: none
server:
  shutdown: graceful
  port: ${SERVER_PORT:8080}
app:
  currency-client:
    base-url: "https://v6.exchangerate-api.com"
    api-key: "f746aba9baf5a10cb9957495"
    enabled: true
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 20
    thread-name-prefix: "currency-async-"
  kafka:
    client-topic-name: "client-lifecycle-events"

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: INFO






